name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Fetch and rebase changes
        run: git fetch origin && git rebase origin/main
        working-directory: /home/ec2-user/klswe

      - name: Install dependencies
        run: npm ci
        working-directory: /home/ec2-user/klswe

      - name: Run tests
        run: npm test
        working-directory: /home/ec2-user/klswe

      - name: Delete old build folder
        run: sudo rm -rf /var/www/build_old

      - name: Move build folder
        run: sudo mv /var/www/build /var/www/build_old

      - name: Build project
        run: npm run build
        working-directory: /home/ec2-user/klswe

      - name: Move Vite build folder
        run: sudo mv ./dist /var/www/build
        working-directory: /home/ec2-user/klswe

      - name: Refresh NGINX
        run: sudo nginx -s reload
