name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "18.19.1"

      - name: Fetch and rebase changes
        run: git fetch origin && git rebase origin/main

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Delete old build folder
        run: sudo rm -rf /var/www/build_old

      - name: Move build folder
        run: sudo mv /var/www/build /var/www/build_old

      - name: Build project
        run: npm run build

      - name: Move Vite build folder
        run: sudo mv ./dist /var/www/build

      - name: Refresh NGINX
        run: sudo nginx -s reload
